[project]
name = "keplaria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=1.0,<2",
    "aiohttp>=3.13.4",
    "gcsfs>=2024.11.0",
    "google-adk[gcp,otel-gcp]>=2.5.0,<3.0.0",
    "opentelemetry-resourcedetector-gcp<=1.12.0a0",
]
